<!DOCTYPE TS><TS version="2.1" language="zh_CN">
<context>
	<name>{"1": "DEVICE_SUB_TYPE_PRO", "2": "DEVICE_SUB_TYPE_PRO_PLUS", "3": "DEVICE_SUB_TYPE_S15", "5": "DEVICE_SUB_TYPE_S20", "6": "DEVICE_SUB_TYPE_S2PLUS", "7": "DEVICE_SUB_TYPE_STOUP", "8": "DEVICE_SUB_TYPE_E3_HX", "9": "DEVICE_SUB_TYPE_E3_H", "10": "DEVICE_SUB_TYPE_E10", "11": "DEVICE_SUB_TYPE_UE", "12": "DEVICE_SUB_TYPE_UE_PRO", "13": "DEVICE_SUB_TYPE_UE_EP", "14": "DEVICE_SUB_TYPE_UE_TRIO", "15": "DEVICE_SUB_TYPE_UE_COMBO"}</name>
	<message>
		<source>EC_CalibrateInit_BoardError-0x3600ff01-prompttext</source>
		<translation>标定板数据错误.</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_BoardError-0x3600ff01-problemdescription</source>
		<translation>标定板文件错误</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_BoardError-0x3600ff01-solution</source>
		<translation>请联系技术支持</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_CamParamError-0x3600ff02-prompttext</source>
		<translation>标定数据错误.</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_CamParamError-0x3600ff02-problemdescription</source>
		<translation>相机内外参数据错误</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_CamParamError-0x3600ff02-solution</source>
		<translation>请联系技术支持</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_LaserParamError-0x3600ff03-prompttext</source>
		<translation>激光标定数据错误!</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_LaserParamError-0x3600ff03-problemdescription</source>
		<translation>光平面标定数据错误</translation>
	</message>
	<message>
		<source>EC_CalibrateInit_LaserParamError-0x3600ff03-solution</source>
		<translation>请联系技术支持</translation>
	</message>
	<message>
		<source>EC_Laser7_CalibrateError05-0x36000707-prompttext</source>
		<translation>七线激光线标定失败.</translation>
	</message>
	<message>
		<source>EC_Laser7_CalibrateError05-0x36000707-problemdescription</source>
		<translation>激光线7线标定失败。加密出现问题</translation>
	</message>
	<message>
		<source>EC_Laser7_CalibrateError05-0x36000707-solution</source>
		<translation>请重试,若连续多次失败,请联系技术支持</translation>
	</message>
	<message>
		<source>EC_UnkonwError-0x3600ffff-prompttext</source>
		<translation>未知错误.</translation>
	</message>
	<message>
		<source>EC_UnkonwError-0x3600ffff-problemdescription</source>
		<translation>未知错误</translation>
	</message>
	<message>
		<source>EC_UnkonwError-0x3600ffff-solution</source>
		<translation>请联系技术支持</translation>
	</message>
	<message>
		<source>Sn3DCalibAlgPoseTrackerError-0x34010101-prompttext</source>
		<translation>标定位姿计算 跟踪标志点失败!</translation>
	</message>
	<message>
		<source>Sn3DCalibAlgPoseTrackerError-0x34010101-problemdescription</source>
		<translation>标志点跟踪失败</translation>
	</message>
	<message>
		<source>Sn3DCalibAlgPoseTrackerError-0x34010101-solution</source>
		<translation>请将设备对准标志点</translation>
	</message>
	<message>
		<source>Sn3DCalibAlgPoseIllegalInput-0x34010102-prompttext</source>
		<translation>标定位姿计算 非法输入.</translation>
	</message>
	<message>
		<source>Sn3DCalibAlgPoseIllegalInput-0x34010102-problemdescription</source>
		<translation>标志点跟踪算法非法输入</translation>
	</message>
	<message>
		<source>Sn3DCalibAlgPoseIllegalInput-0x34010102-solution</source>
		<translation>确认算法初始化正确</translation>
	</message>
</context>
</TS>
